import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs"
import { queryFetcher, contactQuery, tabsQuery} from "./queries";
import {frFR} from "@clerk/localizations"
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tabs = await queryFetcher(tabsQuery)
  const contacts = await queryFetcher(contactQuery)

  return (
    <ClerkProvider localization={frFR}>
      <html lang="en">
        <body>
          <Header tabs={tabs} />
          {children}
          <Footer tabs={tabs} contacts={contacts} />
        </body>
      </html>
    </ClerkProvider>
  );
}
