import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs"
import { queryFetcher, contactQuery, menuQuery, bannerQuery} from "./queries";
import {frFR} from "@clerk/localizations"
import "./globals.css";
import "./homepage.css";
import "./services.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Banner from "./components/Banners";

export const metadata: Metadata = {
  title: "Maison de la Famille de St-François",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tabsQuery = await queryFetcher(menuQuery)
  const contacts = await queryFetcher(contactQuery)
  const banner = await queryFetcher(bannerQuery)

  const tabs = tabsQuery.flatMap((tab: { pages: string[] }) => tab.pages)

  return (
    <ClerkProvider localization={frFR}>
      <html lang="en">
        <body>
          <Header tabs={tabs} />
          <Banner banner={banner[0]?.bannerList ?? []} />
          {children}
          <Footer tabs={tabs} contacts={contacts} />
        </body>
      </html>
    </ClerkProvider>
  );
}
